"""Measured access verification, in the C.1 pattern: measured, not documented.

Every source reports what is reachable, at what measured rate, and at what
cost. **A source that fails verification is reported and dropped, not worked
around silently** — its row stays in the table with ``reachable=False`` and a
stated reason, so a later reader can see what was tried.

The table is written to ``docs/ACCESS.md`` and the raw rows to the ledger-side
store, so a claim in the report can always be traced to a measurement.
"""

from __future__ import annotations

from pathlib import Path

from solattn import registry
from solattn.clock import Clock, iso
from solattn.config import Settings
from solattn.http import PacedClient
from solattn.records import AccessResult
from solattn.sources import bluesky, farcaster, geckoterminal, solbench, telegram


def run_all(
    client: PacedClient,
    clock: Clock,
    settings: Settings,
    channels: list[str] | None = None,
    firehose_seconds: float = 10.0,
) -> list[AccessResult]:
    """Verify every source by measurement. Failures are results, not exceptions."""
    results: list[AccessResult] = []

    for name, thunk in (
        ("geckoterminal", lambda: geckoterminal.verify(client, clock)),
        ("solbench", lambda: solbench.verify(client, clock)),
        ("farcaster", lambda: farcaster.verify(client, clock)),
        ("bluesky", lambda: bluesky.verify(clock, firehose_seconds)),
        (
            "telegram",
            lambda: telegram.verify(
                clock,
                settings.telegram_api_id,
                settings.telegram_api_hash,
                settings.telegram_session,
                channels,
            ),
        ),
    ):
        try:
            results.extend(thunk())  # type: ignore[no-untyped-call]
        except Exception as exc:
            results.append(
                AccessResult(
                    source=name,
                    endpoint="(verification raised)",
                    reachable=False,
                    measured_rate="n/a",
                    measured_limit="n/a",
                    cost="n/a",
                    detail=f"{type(exc).__name__}: {exc}",
                    measured_at=iso(clock.now()),
                )
            )
    return results


def render_table(results: list[AccessResult], clock: Clock) -> str:
    """Render the access table. Every row carries its measurement time."""
    lines = [
        "# ACCESS.md — the measured access table",
        "",
        "**Measured, not documented.** Every row here was produced by an actual probe",
        "against the live source. A published rate limit or a documented endpoint is",
        "not believed until it is measured, and **a source that fails verification is",
        "reported and dropped, not worked around silently.**",
        "",
        f"Generated by `make verify` at {iso(clock.now())}.",
        "",
        "| source | endpoint | reachable | measured rate | measured limit | cost |",
        "|---|---|---|---|---|---|",
    ]
    for row in results:
        mark = "yes" if row.reachable else "**NO**"
        lines.append(
            f"| {row.source} | `{row.endpoint}` | {mark} | {row.measured_rate} | "
            f"{row.measured_limit} | {row.cost} |"
        )
    lines.extend(["", "## Per-source detail", ""])
    for row in results:
        lines.extend(
            [
                f"### {row.source} — `{row.endpoint}`",
                "",
                f"- reachable: **{'yes' if row.reachable else 'no'}**",
                f"- measured rate: {row.measured_rate}",
                f"- measured limit: {row.measured_limit}",
                f"- cost: {row.cost}",
                f"- detail: {row.detail}",
                f"- measured at: {row.measured_at}",
                "",
            ]
        )

    dropped = [r for r in results if not r.reachable]
    lines.extend(
        [
            "## Sources dropped at verification",
            "",
        ]
    )
    if dropped:
        for row in dropped:
            lines.append(f"- **{row.source}** (`{row.endpoint}`) — {row.detail}")
    else:
        lines.append("- none; every probed source verified.")
    lines.extend(
        [
            "",
            "## Registered capacity these measurements feed",
            "",
            f"- GeckoTerminal pacing **{registry.GECKOTERMINAL_MIN_SPACING_S:.1f}s** minimum "
            f"→ {int(86400 / registry.GECKOTERMINAL_MIN_SPACING_S):,} requests/day capacity, "
            f"daily cap **{registry.GECKOTERMINAL_DAILY_CAP:,}**.",
            f"- Universe watcher: a sweep every {registry.WATCH_SWEEP_SECONDS}s × "
            f"{registry.WATCH_PAGES_PER_SWEEP} pages = "
            f"{int(86400 / registry.WATCH_SWEEP_SECONDS) * registry.WATCH_PAGES_PER_SWEEP:,} "
            f"requests/day.",
            f"- Outcome checkpoints at T0+{registry.CHECKPOINT_DAYS[0]}d and "
            f"T0+{registry.CHECKPOINT_DAYS[1]}d = 2 calls per pool "
            f"→ ~{registry.EXPECTED_AMM_POOLS_PER_DAY * 2:,} requests/day at the "
            f"registered ~{registry.EXPECTED_AMM_POOLS_PER_DAY:,} AMM births/day.",
            "",
        ]
    )
    return "\n".join(lines) + "\n"


def write_table(results: list[AccessResult], clock: Clock, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_table(results, clock), encoding="utf-8")
    return path
